---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: demo-app-two
  namespace: flux-system
spec:
  image: bishalkc/demo-app
  interval: 30s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: demo-app-two
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-app-two
  filterTags:
    pattern: "^dev-[a-f0-9]+-(?P<ts>[0-9-]+)"
    extract: "$ts"
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: demo-app-two
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: demo-flux
  git:
    checkout:
      ref:
        branch: main ### DONT CHANGE THIS
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: main ### DONT CHANGE THIS
  update:
    path: ./apps/demo-app-two/dev/app.yaml
    strategy: Setters
