apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

  ## Demo APP
  - ../../../src/dev/demo-app.yaml
  - ../../../demo-app/dev/app.yaml
