apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

  ## Notification
  - ./notifications/notify.yaml

  ## Demo APP ONE
  - ./src/one/dev/src.yaml
  - ./src/one/dev/image-watch.yaml
  - ./apps/one/dev/app.yaml

  ## Demo APP ONE
  # - ./src/two/dev/src.yaml
  # - ./src/two/dev/image-watch.yaml
  # - ./apps/two/dev/app.yaml
