apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

  ## Notification
  - ../../../notifications/notify.yaml

  ## Demo APP ONE
  - ../../../src/demo-app-one/dev/src.yaml
  - ../../../src/demo-app-one/dev/image-watch.yaml
  - ../../../apps/demo-app-one/dev/app.yaml

  ## Demo APP ONE
  # - ./src/demo-app-two/dev/src.yaml
  # - ./src/demo-app-two/dev/image-watch.yaml
  # - ./apps/demo-app-two/dev/app.yaml
