---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 3m
  releaseName: demo-app
  targetNamespace: demo-app
  chart:
    spec:
      chart: ./helmchart/
      sourceRef:
        kind: GitRepository
        name: demo-app
        namespace: flux-system
      interval: 3m
  values:
    namespace: demo-app
    generatecert:
      enabled: true
    hpa:
      enabled: true
      minReplicas: 3
    # service:
    #   name: demo-app-dev
    # serviceAccount:
    #   name: demo-app-dev-sa
    image:
      repository: "bishalkc/demo-app"
      tag: "v11"
    app:
      environment: dev
      port: 8080
      project: "demo-app"
      tenant: "DA"
      framework: "demo"
      cluster_name: "demo-cluster"
      secrets:
        manager:
          enabled: true
          name: "database-v5"
          type: "aws"
        ssm:
          enabled: true
          params:
            - name
            - environment
            - framework
            - api_key
            - hash_key
