apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 30s
  releaseName: demo-app
  targetNamespace: demo-app
  chart:
    spec:
      chart: ./helmchart/
      sourceRef:
        kind: GitRepository
        name: demo-app
        namespace: flux-system
      interval: 30s
  values:
    namespace: demo-app
    #########---- Default values for Kubernetes object: Service ----#########
    service:
      type: "ClusterIP"
      port: 80
      targetPort: 8080
      protocol: "TCP"
    #########---- Default values for Kubernetes object: Deployment ----#########
    image:
      repository: "bishalkc/demo-app"
      tag: "bishalkc/demo-app:v1.0.3" # {"$imagepolicy": "flux-system:demo-app:tag"}
    containers:
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      ports:
        name: "http"
        containerPort: 8080
        protocol: "TCP"
      resources:
        limits:
          cpu: 200m
          memory: "200Mi"
        requests:
          cpu: 50m
          memory: "50Mi"
    readinessProbe:
      path: /health/readiness
      port: 8080
      scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 5
      successThreshold: 2
      failureThreshold: 2
    livenessProbe:
      path: /health/liveness
      port: 8080
      scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 15
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 2
    #########---- Default values for Kubernetes object: HorizontalPodAutoscaler (hpa) ----#########
    hpa:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      metrics:
        cpuUtilizationPercentage: 80
        memoryUtilizationPercentage: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
          policies:
            type: Percent
            value: 100
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            type: Pods
            value: 3
            periodSeconds: 60
    #########---- Default values for Kubernetes object: serviceAccount ----#########
    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # name: "demo-app"
      automount: true
      # aws_region: "us-east-1"
      # aws_account_id: "646431313"
    #########---- Default LB/Ingress ----#########
    ingress:
      enabled: false
      className: "alb"
      albName: "demo-app-dev"
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      hosts:
        - host: hello.test.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      inbound_cidrs: {}
      # enabled: false
      # cidrs: ""
      alb:
        enabled: true
        # enabled: false
        # delete_protection: false
      ssl: {}
      # enabled: false
      # port: 443
    #########---- Default values app ----#########
    app:
      environment: dev
      port: 8080
      project: "demo-app"
      framework: "demo"
      # cluster_name: "demo-cluster"
      secrets:
        manager:
          enabled: true
          name: "database-v5"
          type: "aws"
        ssm:
          enabled: true
          params:
            - name
            - environment
            - framework
            - api_key
            - hash_key
