apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app-one # {project_name}-{app_name}
  namespace: flux-system
spec:
  interval: 30s
  releaseName: demo-app-one # {project_name}-{app_name}
  targetNamespace: demo-app-one # {project_name}-{app_name}
  chart:
    spec:
      chart: ./helmchart/
      sourceRef:
        kind: GitRepository
        name: demo-app-one
        namespace: flux-system
      interval: 30s
  values:
    namespace: demo-app-one
    image:
      repository: "bishalkc/demo-app"
      tag: "dev-a5d10b4-20230701-010656" # {"$imagepolicy": "flux-system:demo-app:tag"}
    app:
      name: "one"
      environment: "dev"
      port: 8080
      project: "demo-app"
      framework: "python"
      # cluster_name: "demo-cluster"
      secrets:
        manager:
          enabled: true
          name: "secrets"
          version: "v2"
          type: "aws"
          params:
            - user
            - password
            - host
            - dbname
        ssm:
          enabled: true
          params:
            - name
            - environment
            - framework
            - api_key
            - hash_key
