apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app-one # {project_name}-{app_name}
  namespace: flux-system
spec:
  interval: 30s
  releaseName: demo-app-one # {project_name}-{app_name}
  targetNamespace: demo-app-one # {project_name}-{app_name}
  chart:
    spec:
      chart: ./helmchart/
      sourceRef:
        kind: GitRepository
        name: demo-app-one
        namespace: flux-system
      interval: 30s
  values:
    namespace: demo-app-one
    image:
      repository: "bishalkc/demo-app"
      tag: "dev-05ab775-20230707-072835" # {"$imagepolicy": "flux-system:demo-app-one:tag"}
      ########---- Default LB/Ingress ----#########
    ingress:
      enabled: true
      className: "alb"
      annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
      hosts:
        - host: "demo-app-one.test.com"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
      inbound_cidrs: {}
      # enabled: false
      # cidrs: ""
      alb:
        enabled: true
        # enabled: false
        # delete_protection: false
      ssl: {}
      # enabled: false
      # port: 443
    ########---- Default values app ----#########
    app:
      name: "one"
      environment: "dev"
      port: 8080
      project: "demo-app"
      framework: "python"
      # cluster_name: "demo-cluster"
      secrets:
        manager:
          enabled: true
          name: "secrets"
          version: "v6"
          type: "aws"
          params:
            - user
            - password
            - host
            - dbname
        ssm:
          enabled: true
          params:
            - name
            - environment
            - framework
            - api_key
            - hash_key
