---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  suspend: false
  interval: 20s
  url: https://github.com/bishalkc/demo-app
  ref:
    branch: main
  secretRef:
    name: git-https-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  image: bishalkc/demo-app
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: demo-app
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: demo-app
  commit:
    authorEmail: bishalkc@gmail.com
    authorName: "Bishal KC"
    messageTemplate: "update image"
  interval: 1m0s
  update:
    strategy: Setters
