---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  suspend: false
  interval: 20s
  url: https://github.com/bishalkc/demo-app
  ref:
    branch: dev
  secretRef:
    name: git-https-credentials
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-flux
  namespace: flux-system
spec:
  suspend: false
  interval: 20s
  url: https://github.com/bishalkc/demo-flux
  ref:
    branch: main
  secretRef:
    name: demo-flux-https-credentials
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  image: bishalkc/demo-app
  interval: 30s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: demo-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demo-app
  filterTags:
    pattern: "^dev-(?P<sha>[a-f0-9]+)"
    extract: "$sha"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: demo-flux
  git:
    checkout:
      ref:
        branch: dev
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: dev
  update:
    path: ./demo-app/dev/app.yaml
    strategy: Setters
